apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          env:
            - name: GCP_PROJECT_ID
              value: "myapp-dev"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
